life_plus_plus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import users,patient,doctor
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),#to go to the admin site
    path('' , include("users.urls")),#default page(page where website loads)
    path('accounts/login/', users.login_view,name='login'),#login the users
    path('accounts/logout/',users.logout_view,name='logout'),#logout the users
    path('accounts/signup/', users.SignUpView.as_view(), name='signup'),#basic signup page,after this asks if you want to register as patient or doctor
    path('accounts/signup/patient/', patient.PatientSignUpView.as_view(), name='patient_signup'),#signup for patient
    path('accounts/signup/doctor/', doctor.DoctorSignUpView.as_view(), name='doctor_signup'),#signup for doctor
    path('record/',include('prescription.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

prescription/urls.py
from django.urls import path
from . import views
app_name = 'prescription'

urlpatterns=[
path('upload/',views.upload,name="upload"),
path('list/',views.record_list,name="list"),
path('delete/<uuid:pk>/',views.delete,name="delete"),
path('ocr/<uuid:pk>',views.ocr,name="ocr"),
path('view/<uuid:pk>/' , views.view , name="view"),
path('download/<uuid:pk>/' , views.download , name="download"),
path('xray/' , views.xray , name="xray"),
path('doctor_view/' , views.doctor_view , name="doctor_view"),
path('xray_list/',views.xray_list,name="xray_list"),
path('xray_delete/<int:pk>/',views.xray_delete,name="xray_delete"),
# path('ocr/<int:pk2>/delete/<int:pk1>',views.delete,name="goback_delete")
]

users/urls.py
from django.urls import path
from .views import users
 
app_name = 'users'

urlpatterns=[
	path('', users.home , name="home"),#website loads here
	# path('register/',views.register_view,name="register"),
	# path('login/',views.login_view,name="login"),
	# path('logout/',views.logout_view,name='logout')
]

templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}EHR{% endblock %}</title>
  <!--  <link rel="icon" href="{% static 'img/favicon.png' %}"> -->
  <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <!-- <script src="'http://code.jquery.com/jquery-2.1.2.min.js's"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>

  <nav>
    <div class="nav-wrapper sticky">
      {% if user.is_authenticated %}
        <div class="container"><a href="{% url 'prescription:list' %}" class="brand-logo left"><em>EHR</em></a></div>
      {% else %}
        <div class="container"><a href="{% url 'users:home' %}" class="brand-logo left"><em>EHR</em></a></div>
      {% endif %}
      <div class="container">
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
          <li><a href="{% url 'prescription:list' %}">{{ user.username }}</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}" class="btn btn-primary" style="border-radius: 30px;">Sign Up</a></li>
          <li><a href="{% url 'login' %}" class="btn btn-primary" style="border-radius: 30px;">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <br>
    <br>
    <br>  
    <div class="container">
      <div class="card-content">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="small material-icons">close</i>
          </button>
        </div>
        {% endfor %}
        {% block content %}
        {% endblock %}
      <!-- <div class="fixed-action-btn">
        <a class="btn-floating btn-large red" href="templates/about.html">
          <i class="large mdi-editor-mode-edit"></i>
        </a>
      </div>   -->
      </div>
    <!-- </div> -->
    <script type="text/javascript" src="js/materialize.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
  <br>
  <br>
  </html>