life_plus_plus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users.views import users,patient,doctor
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),#to go to the admin site
    path('' , include("users.urls")),#default page(page where website loads)
    path('accounts/login/', users.login_view,name='login'),#login the users
    path('accounts/logout/',users.logout_view,name='logout'),#logout the users
    path('accounts/signup/', users.SignUpView.as_view(), name='signup'),#basic signup page,after this asks if you want to register as patient or doctor
    path('accounts/signup/patient/', patient.PatientSignUpView.as_view(), name='patient_signup'),#signup for patient
    path('accounts/signup/doctor/', doctor.DoctorSignUpView.as_view(), name='doctor_signup'),#signup for doctor
    path('record/',include('prescription.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

prescription/urls.py
from django.urls import path
from . import views
app_name = 'prescription'

urlpatterns=[
path('upload/',views.upload,name="upload"),
path('list/',views.record_list,name="list"),
path('delete/<uuid:pk>/',views.delete,name="delete"),
path('ocr/<uuid:pk>',views.ocr,name="ocr"),
path('view/<uuid:pk>/' , views.view , name="view"),
path('download/<uuid:pk>/' , views.download , name="download"),
path('xray/' , views.xray , name="xray"),
path('doctor_view/' , views.doctor_view , name="doctor_view"),
path('xray_list/',views.xray_list,name="xray_list"),
path('xray_delete/<int:pk>/',views.xray_delete,name="xray_delete"),
# path('ocr/<int:pk2>/delete/<int:pk1>',views.delete,name="goback_delete")
]

users/urls.py
from django.urls import path
from .views import users
 
app_name = 'users'

urlpatterns=[
	path('', users.home , name="home"),#website loads here
	# path('register/',views.register_view,name="register"),
	# path('login/',views.login_view,name="login"),
	# path('logout/',views.logout_view,name='logout')
]

prescription/models.py
from django.db import models
import uuid
from users.models import (User)

class Prescriptions(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	record = models.CharField(max_length=100)#check out about the unique field
	image = models.ImageField(upload_to='documents/',blank=False)
	username = models.ForeignKey(User,default=None,on_delete=models.PROTECT)
	text = models.TextField(default="")
	name = models.CharField(default="name",max_length=100)
	def __str__(self):
		return self.record
		
	def delete(self,*args,**kwargs):
		self.image.delete()
		super().delete(*args,**kwargs)
# Create your models here.
#Model prescription.
class XRay(models.Model):
	image = models.ImageField(upload_to='xrays/',blank=False)
	username = models.ForeignKey(User,default=None,on_delete=models.PROTECT)
	name = models.CharField(default="name",max_length=100)
	predictions = models.TextField(default="")
	def __str__(self):
		return self.image.path

	def delete(self , *args , **kwargs):
		self.image.delete()
		super().delete(*args,**kwargs)	 

prescription/forms.py
from django import forms
from . import models

class UploadPrescription(forms.ModelForm):
	class Meta:
		model=models.Prescriptions
		fields = ['image','record','name']#required fields(input by user)

class VerifyOCRText(forms.ModelForm):
	class Meta:
		model=models.Prescriptions
		fields = ['text']	

class UploadXRay(forms.ModelForm):
	class Meta:
		model = models.XRay
		fields = ['image','name']	

prescription/views.py
from utils import prescription , blockchain ,x_ray
from django.shortcuts import render,redirect
from .models import Prescriptions ,XRay
from . import forms
from django.core.files.storage import FileSystemStorage
from PIL import Image
import pytesseract
from django.http import HttpResponse , HttpResponseRedirect
from web3 import Web3
import json
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import web3
# Create your views here.

# contract_address="0x68C7375827709848F649C2996fC806d10D5514d6"
path = "./model.h5"
print("THIS WORKS")
flag1=False

# Create your views here.
@login_required
def record_list(request):
	trial = prescription.Prescription()
	prescriptions = trial.record_list(request)
	return render(request,'prescription/prescription_list.html',{'prescriptions':prescriptions})

@login_required
def upload(request):
	trial = prescription.Prescription()
	form ,pk = trial.upload(request)
	if pk!=-1:
		# return redirect('prescription:ocr/'+str(pk))
		print("a")
		return HttpResponseRedirect(reverse('prescription:ocr' , args=(pk,)))
		
	else:
		print("b")
		return render(request,'prescription/prescription_upload.html',{'form':form})
		
@login_required
def delete(request,pk):
	trial = prescription.Prescription()
	trial.delete_record(request,pk)
	# pk1 = kwargs.get('pk1', none) 
	return redirect('prescription:list')

@login_required
def ocr(request,pk):
	if request.method == "GET":	
		trial = prescription.Prescription()
		ocr_instance = trial.ocr(request,pk)
		# pk2 = kwargs.get('pk2', none) 
		text = ocr_instance[0]
		prescriptions = ocr_instance[1]
	

	elif request.method == "POST":
		# form = forms.VerifyOCRText(request.POST , request.FILES)
		# if form.is_valid():
		instance = Prescriptions.objects.get(pk = pk)
		if instance is not None:
			instance.text = request.POST.get('ocr-text' , "")
			instance.save()

			instance = Prescriptions.objects.get(pk=pk)
			text = instance.text
			web3 = Web3()
			hash_hex = web3.keccak(text=text).hex()
			# print(hash_hex)
			# print(hash_)
			# print(len(hash_hex))
			if flag1==False:
				b = blockchain.Blockchain(url="http://127.0.0.1:7545" , abi=abi)
				# flag1=True
			if b.connect():
				inserted = b.insert_hash(hash_hex)
				print(inserted)
				if inserted:
					return redirect('prescription:list')
				else:
					return HttpResponse('<h1>Push to blockchain failed</h1>')
			else:
				return HttpResponse("<h1>Connection failed</h1>")



			# return redirect('prescription:block' , args=(pk))
			# return render(block(request,pk))
		else:
			return HttpResponse("<h1>Instance is null</h1>")	
	
	return render(request,'prescription/prescription_ocr.html',{'prescriptions':prescriptions,'text':text })


@login_required
def download(request,pk):
	instance = Prescriptions.objects.get(pk=pk)
	text = instance.text
	web3= Web3()
	hash_hex = web3.keccak(text=text).hex()
	if flag1==False:
		b = blockchain.Blockchain(url="http://127.0.0.1:7545", abi=abi)
		# flag1=True
	b.connect()
	exists = b.check_hash(hash_hex)

	if exists:
		return render(request , 'prescription/prescription_download.html' ,{"prescription":instance} )
	else:
		return HttpResponse("<h1>Hash does not exist in blockchain</h1>")	

@login_required
def view(request,pk):
	trial = prescription.Prescription()
	print(trial)
	(exists , instance) = trial.view(request,pk)
	if exists:
		return render(request , 'prescription/prescription_view.html' , {'prescription':instance})
	else:
		return HttpResponse("<h1>Hash does not exist in blockchain</h1>")	
	

@login_required
def doctor_view(request):
	if request.method=="POST":
		trial = prescription.Prescription()
		print(trial)
		pk = request.POST["pk"]
		(exists , instance) = trial.view(request,pk)
		if exists:
			return render(request , 'prescription/prescription_view.html' , {'prescription':instance})
		else:
			return HttpResponse("<h1>Hash does not exist in blockchain</h1>")	

@login_required
def xray(request):
	trial = x_ray.XRay_class()
	form , pk = trial.upload_xray(request)

	if pk!=-1:
		print(pk)
		obj = XRay.objects.get(pk=pk)

		pred = trial.get_results(request , path)   
		print(pred)
		print(obj.predictions)
		obj.predictions = pred
		obj.save()
		image_path = obj.image.url
		return render(request , "prescription/xray_result.html" , {"image_path":image_path,"predictions":pred})	

	# pred = "Nahi aaya"
	return render(request , "prescription/xray_upload.html" , {"form":form})

@login_required
def xray_list(request):
	trial = x_ray.XRay_class()
	xray = trial.xray_list(request)
	return render(request,'prescription/xray_list.html',{'xray':xray})

@login_required
def xray_delete(request,pk):
	# print("deelte ho rha hai" , pk)
	trial = x_ray.XRay_class()
	trial.delete_xray(request,pk)
	return redirect('prescription:xray_list')

bytecode = "608060405234801561001057600080fd5b506101c6806100206000396000f3fe608060405260043610610046576000357c01000000000000000000000000000000000000000000000000000000009004806366e34cf11461004b578063af5135fd1461009e575b600080fd5b34801561005757600080fd5b506100846004803603602081101561006e57600080fd5b81019080803590602001909291905050506100f1565b604051808215151515815260200191505060405180910390f35b3480156100aa57600080fd5b506100d7600480360360208110156100c157600080fd5b8101908080359060200190929190505050610140565b604051808215151515815260200191505060405180910390f35b60006100fc82610140565b1561010a576000905061013b565b6000829080600181540180825580915050906001820390600052602060002001600090919290919091505550600190505b919050565b60008060009050600090505b60008054905081101561018f578260008281548110151561016957fe5b90600052602060002001541415610184576001915050610195565b80600101905061014c565b60009150505b91905056fea165627a7a72305820577f0c80bf483610360752f4736f01428e4edf66c5102792faaf73951fb4cf2b0029"

abi = json.loads("""[
	{
		"constant": false,
		"inputs": [
			{
				"name": "hash",
				"type": "bytes32"
			}
		],
		"name": "add_hash",
		"outputs": [
			{
				"name": "",
				"type": "bool"
			}
		],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [],
		"payable": false,
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"constant": true,
		"inputs": [
			{
				"name": "hash",
				"type": "bytes32"
			}
		],
		"name": "check_existence",
		"outputs": [
			{
				"name": "",
				"type": "bool"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	}
]""")	

prescription/templates/prescription/prescription_download.html
{% extends 'base.html' %}
{% block content %}
<div>
	<h2>Click on the link below to download</h2>
	<p><a class ="download" href="{{prescription.image.url}}" class="btn-large">Download {{prescription.image}}</a></p>
</div>
<br>
<br>
<div class="back">
	<form class="back_form" action="{% url 'prescription:view' prescription.pk  %}" method="post">
		{% csrf_token %}
		<input type="submit" class="btn-large" style="border-radius: 20px;"value="Go Back">
	</form>
</div>
{% endblock content %}

prescription/templates/prescription/prescription_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<h1>Records Uploaded </h1>
	<div class="prescriptions">
		{% for prescription in prescriptions %}
			{% if user.is_authenticated %}
				{% if request.user == prescription.username %}
			<div class ="card hoverable">
				<div class="card-content">
					<i class="medium material-icons">content_paste</i>
					<div class="prescription">
						<h2 style="color:black">Prescription Name:  {{prescription.record}}</h2>
						{% if user.is_patient %}
							<h3>Prescribed By Doctor:  {{prescription.name}}</h3>
						{% else %}
							<h3>Prescribed For Patient:  {{prescription.name}}</h3>
						{% endif %}
						<!-- <p><a class ="download" href="{{prescription.image.url}}" class="btn btn-primary btn-sm">Download {{prescription.image}}</a></p> -->
						<a href="{% url 'prescription:download' prescription.pk %}"><button class="btn-large" style="border-radius: 20px;">Download</button></a>
						<a href="{% url 'prescription:view' prescription.pk %}"><button class="btn-large" style="border-radius: 20px;">View</button></a>
						<button class="btn-large copy-btn" style="border-radius: 20px;"data-pk="{{ prescription.pk }}">Copy Unique Key</button>
						<br>
						<br>
						<div class="delete">
							<form class="delete_form" action="{% url 'prescription:delete' prescription.pk %}" method="post">
								{% csrf_token %}
								<input type="submit" class="btn-large" style="border-radius: 20px;" value="Delete">
							</form>
						</div>
					</div>
				</div>
			</div>
					<br>
					<br>
				{% endif %}
			{% endif %}
		{% endfor %}
	</div>
	<!-- <h1>XRays Uploaded </h1> -->
	<!-- <h1>Upload new XRay</h1> -->
	<h1>Upload new Prescription</h1>
		<a href="{% url 'prescription:upload'%}"><button class=" btn-large" style="border-radius: 20px;">Upload Prescriptions</button></a>
	<h1>Upload new XRay</h1>
		<a href="{% url 'prescription:xray'%}"><button class="btn-large" style="border-radius: 20px;">Upload XRay</button></a>
	<h1>View Previous XRay's</h1>
		<a href="{% url 'prescription:xray_list' %}"><button class="btn-large" style="border-radius: 20px;">Uploaded XRay's</button></a>
	<h1>Access a Prescription</h1>
	<form action="/record/doctor_view/" method="POST">
		{% csrf_token %}
		<input type="text" class="input" style="color:#fff" name="pk" />
		<button type="submit" class="btn-large" style="border-radius: 20px;">Access</button>
	</form>
	<script>
		  let copyBtns = document.querySelectorAll('.copy-btn');
        copyBtns.forEach(btn => {
            btn.addEventListener('click', () => {
                let pk = btn.getAttribute('data-pk');
                let tempInput = document.createElement('input');
                tempInput.value = pk;
                document.body.appendChild(tempInput);
                tempInput.select();
                document.execCommand('copy');
                document.body.removeChild(tempInput);
                alert('Copied PK: ' + pk);
            });
        });
		</script>
{% endblock %}

prescription/templates/prescription/prescription_ocr.html
{% extends 'base.html' %}
{% block content %}
<h1>Previous Records</h1>
<form method="POST" action="{% url 'prescription:ocr' prescriptions.pk %}">
	{% csrf_token %}
	<div class="prescriptions">
		{% if user.is_authenticated %}
		{%if request.user == prescriptions.username %}
		<div class="prescription">
			<h1><p>{{prescriptions.record}}</p></h1>
			<p>{{prescription.username}}</p>
			<div id="ocr_text">
				<textarea style="background-color: white;" id="textarea1" class="materialize-textarea" name="ocr-text">{{text}}</textarea>
			</div>	<!-- <p>{{prescriptions}}</p> -->
		</div>
		{% endif %}
		{% endif %}
	</div>
	<div>
		<input type="submit" class="btn-large" style="border-radius: 20px;"value="Submit"></input>
	</div>
</form>	
<!-- <form method="POST" action="{url 'prescription:goback_delete' prescriptions.pk %}">
	<input type="submit" class="btn-large" value="Go Back">
</form> -->
<!-- </div> -->
<br>
<div class="back">
	<form class="back_form" action="{% url 'prescription:list'  %}" method="post">
		{% csrf_token %}
		<input type="submit" class="btn-large pulse" style="border-radius: 20px;"value="Go Back">
	</form>
</div>
{% endblock %}

prescription/templates/prescription/prescription_upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<h1>Upload new Prescription</h1>
<div class="create-prescription">
	<div class="card hoverable">
		<div class="card-content">
			<form class="site-form" action="{% url 'prescription:upload' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{% if user.is_patient %}
				<p>Enter the Doctor Name In the last field</p>
				{% else %}
				<p>Enter the Patient Name In the last field</p>
				{% endif %}
				{{form|crispy}}
				<br>
				<br>
				<input type="submit" class="btn-large" style="border-radius: 20px;"value="Upload">
			</form>
		</div>
	</div>
</div>
<br>
<br>
<div class="back">
	<a href="{% url 'prescription:list'%}"><button class="btn btn-primary btn-large pulse">Go Back</button></a>
</div>

{% endif %}
{% endblock %}

prescription/templates/prescription/prescription_view.html
{% extends 'base.html' %}
{% block content %}
	<i class="large material-icons" style="color:white">image</i>
	<br>
	<br>
	<div>
		<h2 style="color:rgb(239, 236, 236)">Prescription Name:  {{prescription.record}}</h2>
						{% if user.is_patient %}
							<h3 style="color:rgb(239, 236, 236)">Prescribed By Doctor:  {{prescription.username}}</h3>
						{% else %}
							<h3 style="color:rgb(239, 236, 236)">Prescribed For Patient:  {{prescription.username}}</h3>
						{% endif %}
		<img class='image'src="{{prescription.image.url}}" style="padding:1px;border:thick solid red;" >
	</div>
	<br>
	<br>
	<div class="back">
		<a href="{% url 'prescription:download' prescription.pk %}"><button class="btn-large"style="border-radius: 20px;">Download</button></a>
		<a href="{% url 'prescription:list'%}"><button class=" btn-large "style="border-radius: 20px;">Go Back</button></a>
	</div>
{% endblock %}

prescription/templates/prescription/xray_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<h1>XRays Uploaded </h1>
	<div class="prescriptions">
		{% for x in xray %}
			{% if user.is_authenticated %}
				{% if request.user == x.username %}
					<div class ="card hoverable">
						<div class="card-content">
							<i class="medium material-icons">content_paste</i>
							<div class="prescription">
								{% if user.is_patient %}
									<h3>XRay By Doctor:  {{x.name}}</h3>
								{% else %}
									<h3>XRay For Patient:  {{x.name}}</h3>
								{% endif %}
								<div>
									<img src="{{x.image.url}}" width=224 height=224>
								</div>
								<div>
									<h3 style="color:black;">This is the prediction</h3>
									<h3 style="color:black;">{{x.predictions}}</h3>
								</div>
								<div>
									<!-- <h1>Delete XRay</h1> -->
								<a href="{% url 'prescription:xray_delete' x.pk %}"><button class="btn-large" style="border-radius: 20px;">Delete XRay</button></a>
								</div>
							</div>
						</div>
					</div>
					<br>
					<br>
				{% endif %}
			{% endif %}
		{% endfor %}
		{% for x in xray %}
			{% if user.is_authenticated %}
				{% if request.user.username == x.name %}
					<div class ="card hoverable">
						<div class="card-content">
							<i class="medium material-icons">content_paste</i>
							<div class="prescription">
								{% if user.is_patient %}
									<h3>XRay By Doctor:  {{x.username}}</h3>
								{% else %}
									<h3>XRay For Patient:  {{x.username}}</h3>
								{% endif %}
								<div>
									<img src="{{x.image.url}}" width=224 height=224>
								</div>
								<div style="color:black;">
									<h3 style="color:black;">This is the prediction</h3>
									<h3 style="color:black!important;">{{x.predictions}}</h3>
								</div>
							</div>
							<!-- <h1>Delete XRay</h1> -->
								<a href="{% url 'prescription:xray_delete' x.pk %}"><button class="btn-large" style="border-radius: 20px;">Delete XRay</button></a>
						</div>
					</div>
					<br>
					<br>
				{% endif %}
			{% endif %}
		{% endfor %}
	</div>
	<h1>Upload new XRay</h1>
		<a href="{% url 'prescription:xray'%}"><button class="btn-large" style="border-radius: 20px;">Upload XRay</button></a>
	<h1>Upload new Prescription</h1>
		<a href="{% url 'prescription:upload'%}"><button class="btn-large" style="border-radius: 20px;">Upload Prescription</button></a>
	<h1>View Previous Prescriptions</h1>
		<a href="{% url 'prescription:list' %}"><button class="btn-large" style="border-radius: 20px;">Uploaded Prescriptions</button></a>
		
{% endblock %}

prescription/templates/prescription/xray_result.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <div>
            <img src="{{image_path}}" width="224" height="224">
        </div>
        <div>
            <p style="color:white;">The prediction is {{predictions}}</p>
        </div>
        <div>
            <h1>View Previous XRay's</h1>
            <a href="{% url 'prescription:xray_list' %}"><button class="btn-large" style="border-radius: 20px;">Uploaded XRay's</button></a>
        </div>
    </div>
{% endblock %}

prescription/templates/prescription/xray_upload.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	{% if user.is_authenticated %}
		<div class="card hoverable">
			<div class="card-content">
				<h1 style="color:black;">Upload X-Ray</h1>
				<div class="create-prescription">
					<form class="site-form" action="{% url 'prescription:xray' %}" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% if user.is_patient %}
						<p>Enter the Doctor Name In the last field</p>
						{% else %}
						<p>Enter the Patient Name In the last field</p>
						{% endif %}
						{{form|crispy}}
						<input type="submit" class="btn-large" style="border-radius: 20px;"value="Upload XRay">
					</form>
				</div>
				<br>
				<div class="back">
					<form class="back_form" action="{% url 'prescription:xray_list'  %}" method="post">
						{% csrf_token %}
						<input type="submit" class="btn-large" style="border-radius: 20px;" value="Go Back">
					</form>
				</div>
			</div>
		</div>

	{% endif %}
{% endblock %}